-- apply changes
alter table aptos modify nivel_id bigint;
alter table aptos modify endereco_id bigint;
alter table aptos drop index uq_aptos_nivel_id_numero;
alter table aptos add constraint uq_aptos_nivel_id_numero unique  (nivel_id,numero);
alter table kardec modify procduto_id bigint;
alter table movprodutos modify movimentacao_id bigint;
alter table movprodutos modify produto_id bigint;
alter table movprodutos drop index uq_movprodutos_produto_id_movimentacao_id;
alter table movprodutos add constraint uq_movprodutos_produto_id_movimentacao_id unique  (produto_id,movimentacao_id);
alter table niveis modify predio_id bigint;
alter table niveis drop index uq_niveis_predio_id_numero_tipo_nivel;
alter table niveis add constraint uq_niveis_predio_id_numero_tipo_nivel unique  (predio_id,numero,tipo_nivel);
alter table predios modify rua_id bigint;
alter table predios drop index uq_predios_rua_id_numero;
alter table predios add constraint uq_predios_rua_id_numero unique  (rua_id,numero);
alter table saldos modify endereco_id bigint;
alter table saldos modify produto_id bigint;
alter table saldos drop index uq_saldos_endereco_id_produto_id;
alter table saldos add constraint uq_saldos_endereco_id_produto_id unique  (endereco_id,produto_id);
alter table transferencias modify mov_produto_id bigint;
alter table transferencias modify endereco_s_id bigint;
