version: "3"
services:
    dep_endereco_v3:
        image: tomcat:8
        container_name: dep_endereco
        ports:
            - "9090:8080"
        environment:
            TZ: "America/Fortaleza"
            EBEAN_PROPS: /etc/ebean.properties
        volumes:
            - ./build/libs/dep_endereco-1.0-SNAPSHOT.war :/usr/local/tomcat/webapps/enderecamento.war
            - ./logs:/usr/local/tomcat/logs
            - ./ebean.properties:/etc/ebean.properties
        restart: always


