package br.com.astrosoft.view.enderecamento.vaadin.views.crudGroup

import br.com.astrosoft.model.enderecamento.domain.Role
import br.com.astrosoft.view.framework.vaadin.menu.ViewMenuItem
import br.com.astrosoft.view.framework.vaadin.views.crud.CrudFields
import br.com.astrosoft.view.framework.vaadin.views.crud.CrudView
import br.com.astrosoft.viewmodel.enderecamento.presenters.crudGroup.CrudGroupViewModel
import com.github.mvysny.karibudsl.v8.AutoView
import com.vaadin.icons.VaadinIcons
import com.vaadin.ui.Grid
import org.vaadin.crudui.form.AbstractAutoGeneratedCrudFormFactory

@AutoView("crudGroups")
@ViewMenuItem(title = "Grupos", icon = VaadinIcons.USERS, grupo = "Segurança",
              order = 11, tags = ["ADM"])
class CrudGroupView : CrudView<CrudGroupViewModel, Role>(CrudGroupViewModel(), Role::class) {
  override val nomeRegistro: String
    get() = "Grupo"
  
  override fun addBuildCrudFields(fields: MutableList<CrudFields>) {
    fields.clear()
    fields.add(CrudFields("name", "Nome do grupo"))
  }
  
  override fun configFormFactory(formFactory: AbstractAutoGeneratedCrudFormFactory<Role>) {}
  
  override fun configGrid(grid: Grid<Role>) {
    grid.addColumn { it.name }
      .caption = "Nome"
  }
  
  override fun updateModel() {}
  
  override fun updateView() {}
}
