package br.com.astrosoft.view.enderecamento.vaadin.views.crudUser

import br.com.astrosoft.model.enderecamento.domain.Role
import br.com.astrosoft.model.enderecamento.domain.User
import br.com.astrosoft.view.framework.vaadin.menu.ViewMenuItem
import br.com.astrosoft.view.framework.vaadin.views.crud.CrudFields
import br.com.astrosoft.view.framework.vaadin.views.crud.CrudView
import br.com.astrosoft.viewmodel.enderecamento.presenters.crudUser.CrudUserViewModel
import com.github.mvysny.karibudsl.v8.AutoView
import com.vaadin.icons.VaadinIcons
import com.vaadin.ui.CheckBoxGroup
import com.vaadin.ui.Grid
import com.vaadin.ui.themes.ValoTheme
import org.vaadin.crudui.form.AbstractAutoGeneratedCrudFormFactory

@AutoView("crudUser")
@ViewMenuItem(title = "Usuários", icon = VaadinIcons.USER, grupo = "Segurança",
              order = 10, tags = ["ADM"])
class CrudUserView : CrudView<CrudUserViewModel, User>(CrudUserViewModel(), User::class) {
  init {
    title = "Editor de usuários"
  }
  
  override fun addBuildCrudFields(fields: MutableList<CrudFields>) {
    fields.clear()
    fields.add(CrudFields("fotoPerfil", "Foto"))
    fields.add(CrudFields("userName", "Usuário"))
    fields.add(CrudFields("chapa", "Chapa"))
    fields.add(CrudFields("title", "Cargo"))
    fields.add(CrudFields("firstName", "Nome"))
    fields.add(CrudFields("lastName", "Sobrenome"))
    fields.add(CrudFields("roles", "Grupos"))
  }
  
  override val nomeRegistro: String
    get() = "Usuário"
  
  override fun configFormFactory(formFactory: AbstractAutoGeneratedCrudFormFactory<User>) {
    formFactory.setFieldProvider("fotoPerfil") {
      val fotoField = FotoField("Foto")
      fotoField
    }
    
    formFactory.setFieldProvider("roles") {
      val listSelect = CheckBoxGroup<Role>("Grupos")
      listSelect.setItemCaptionGenerator { r -> r.name }
      listSelect.setItems(model.grupos())
      listSelect.addStyleName(ValoTheme.OPTIONGROUP_HORIZONTAL)
      listSelect
    }
  }
  
  override fun configGrid(grid: Grid<User>) {
    grid.addColumn<String> { it.chapa }
      .caption = "Chapa"
    grid.addColumn<String> { it.userName }
      .caption = "Usuário"
    grid.addColumn<String> { it.firstName }
      .caption = "Nome"
    grid.addColumn<String> { it.lastName }
      .caption = "Sobrenome"
    grid.addColumn<String> { it.title }
      .caption = "Cargo"
  }
  
  override fun updateView() {}
  
  override fun updateModel() {}
}
